### ISSUE TITLE
Import historical data to elasticsearch

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#119]

**Comment by tomarcafe** [comment]
cannot find any db at the instance

**Comment by 21xhipster** [comment]
lol. That means that task has been transformed to "Import historical data to elasticsearch" with low priority. Are you sure that it doesn't exist now? Can we delete instances?

**Comment by tomarcafe** [comment]
well i check out path that is set as dbPath in mongo config files - no such folder
so, yes - nothing left here..
