### ISSUE TITLE
Infinite "Calculating stuff" on Chrome for Android

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#152]

**Comment by tomarcafe** [comment]
not reproduced on chrome beta.
not reproduced on chrome, also. 
not sure how to fix, then.

**Comment by tomarcafe** [comment]
chrome version 43.0.2357.93

**Comment by tomarcafe** [comment]
is it still there?

**Comment by 21xhipster** [comment]
It seems that it begin to work!
