### ISSUE TITLE
Fix the recording information about Supply and Cap for NOTE | BitShares Music

### ISSUE THREAD

**Issue by vitalylvov** [cyberFund/cyber.fund#168]
At the moment we receive not all data for this system:
```
"name":"NOTE"
"symbol":"NOTE"
"availableSupply":"?"
"marketCap":{"usd":"0.0","btc":"?",....}
"price":{"usd":"0.00086624","btc":"3.15313e-06",...}
```
By this reason we take info about MarketCap and Supply from ChainGear
But this is a mistake on the side of information provider and we have to solve independently

In this situation better to take supply from ChainGear and calculate MarketCap like that:
index.cyber.fund `supply_current` = chaingear `specs.supply`
index.cyber.fund `cap_btc` = chaingear `specs.supply` * CMC `price.btc`

**Comment by 21xhipster** [comment]
Actual bug is fixed [here](https://github.com/cyberFund/api.cyber.fund/issues/6)
