### ISSUE TITLE
Icons for "standart" links

### ISSUE THREAD

**Issue by vitalylvov** [cyberFund/cyber.fund#188]
для "стандартных" ссылок использовать иконки из font awesome:
`website` - fa-home
`paper` - fa-graduation-cap
`wallet` - fa-credit-card
`explorer` - fa-search
`wiki` - fa-wikipedia-w
`github` - fa-github
`twitter` - fa-twitter
`reddit` - fa-reddit
`blog` - fa-pencil-square-o
`forum` - fa-comments-o

**Comment by 21xhipster** [comment]
@lomashuk Keep in mind that there are standard icons
