### ISSUE TITLE
Add 3 digits separated by space to USD price if value > $0.1

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#191]
![screen shot 2015-08-10 at 15 48 31](https://cloud.githubusercontent.com/assets/410789/9174370/4a4bcb6a-3f77-11e5-9dd0-d4cab96ab3eb.png)

**Comment by tomarcafe** [comment]
пример разметки?
`$ 0.0123 ` или как конкретно

**Comment by 21xhipster** [comment]
`$ 0.01 123`
