### ISSUE TITLE
Cap stuck for BitShares Music

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#192]
After removing hardcoded cap from chaingear

**Comment by tomarcafe** [comment]
http://index.cyber.fund/#/discover?_g=(refreshInterval:(display:Off,section:0,value:0),time:(from:'2015-08-11T11:20:02.000Z',mode:absolute,to:'2015-08-11T11:20:03.000Z'))&_a=(columns:!(_source),index:marketcap-read,interval:auto,query:(query_string:(analyze_wildcard:!t,query:Music)),sort:!(timestamp,desc))

вот какие данные приходят в еластик. можно видеть что они нулёвые

**Comment by 21xhipster** [comment]
Договорились что в случае если супплая нет ни в одном источнике, парсер берет данные из chaingear и рассчитывает капитализацию.
