### ISSUE TITLE
Cannot edit asset

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#198]
![screen shot 2015-08-20 at 15 26 26](https://cloud.githubusercontent.com/assets/410789/9385796/455ae5c4-4750-11e5-9249-f9644ec9874d.png)
Actions:
1. Add bitcoin
2. Balance has been updated
3. Change balance for bitcoin
4. Use button to update balance
5. Buttons  for CFUND dissapear
6. Editiing works for assets added aftewards

**Comment by tomarcafe** [comment]
works as intended. we just have auto-update there.
also, edit does not work.. well but "add" overwrites current value for
existing coins
