### ISSUE TITLE
Add tiny charts to rating

### ISSUE THREAD

**Issue by lomashuk** [cyberFund/cyber.fund#201]

**Comment by 21xhipster** [comment]
Надо всё таки сделать это по-человечески как на CMC а не в тултипе, т.к. цель этих графиков быстро понять что растет а что падает. В тултипу утилити этих графиков очень низкий.

**Comment by tomarcafe** [comment]
в тултип это было вынесено чтоб Валера сделал презентацию.

**Comment by tomarcafe** [comment]
и на деве оно так и осталось

**Comment by 21xhipster** [comment]
Вот речь о том, что оно не должно так остаться. Нужно чтобы в отдельном столбике по-человечески отображалось

**Comment by tomarcafe** [comment]
что?

**Comment by 21xhipster** [comment]
coinmarketcap.com - вот как там

**Comment by tomarcafe** [comment]
ну сделай :) че там сложного-то. отдельный шаблон. рядом цсс.

**Comment by 21xhipster** [comment]
Я не нашел, где этот код :-1:

**Comment by tomarcafe** [comment]
окей

**Comment by 21xhipster** [comment]
И еще микропросьба. Рамочку у этих графиков можно убрать?

**Comment by tomarcafe** [comment]
grep -r . -e ">quickchart"

**Comment by 21xhipster** [comment]
Это он на меня еще за AIP ругается!! Что это такое?

**Comment by tomarcafe** [comment]
ну

**Comment by tomarcafe** [comment]
grep -r client/ -n -e "> quickchart"

**Comment by 21xhipster** [comment]
Теперь та конечно намного понятнее :-(

**Comment by tomarcafe** [comment]
запусти с консоли из папки проекта :)

**Comment by tomarcafe** [comment]
вообще, я б ее убрал в 1d change. смысел то тот же.

**Comment by 21xhipster** [comment]
А че - отличная идея!
