### ISSUE TITLE
Autoupdate don't work until owner login in

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#217]
If money sent to address that is public, balance won't updated until owner of this address log into cyber•Fund

**Comment by tomarcafe** [comment]
hmm. works as designed (so far)

**Comment by 21xhipster** [comment]
Understood. I suppose that one day we'll should redesign

**Comment by tomarcafe** [comment]
well. we can trigger autoupdates from many events - for example someone looking someone other profile. - we can trigger that other profile accounts to autouupdate. 
or simply use timer. but i m not sure if resulting load is fine. however, we can experiment with such things

**Comment by tomarcafe** [comment]
closed for #355 duplicates it.
