### ISSUE TITLE
Fix adding BitShares Music in Portfolio

### ISSUE THREAD

**Issue by vitalylvov** [cyberFund/cyber.fund#223]
При добавлении в портфель Bitshares Music добавляется DNotes
![adding bts music](https://cloud.githubusercontent.com/assets/925692/9732717/b23d1d0a-562e-11e5-8d08-cf2bb83f0ce7.png)
![adding bts music result](https://cloud.githubusercontent.com/assets/925692/9732723/bb3415bc-562e-11e5-9fb0-86a5310f443d.png)

Причина: одинаковые `token_symbol` = `NOTE`

**Comment by tomarcafe** [comment]
моё глубокое убеждение - что нужно делать разные тикеры для всего.

**Comment by 21xhipster** [comment]
Есть проблема: (1) рынок уже решил что есть так. (2) общепризнанное определние тикера говорит о том, что тикер является уникальным id на уникальном рынке (взято из вики). @tomarcafe Что делать?

**Comment by tomarcafe** [comment]
хм. ну какое-то время - точно страдать. таки, система хранения сейчас опирается на тикеры. 
так 2 одинаковых тикера NOTE - они не вяжутся с (2) - или мы там имеем разные рынки?
добавить _ к одному из тикеров  - не вариант?

**Comment by tomarcafe** [comment]
я бы сделал так: конфликтующие тикеры развязал, добавлением _подчерка в конец - т.е. NOTE, NOTE_, NOTE__. - для софта это бы решило проблему - у нас бы оказались уникальные ключи, можно было бы с ними работать. позже, если кому-то покажется некрасивым допиливать то, что рынок решил - вполне можно для _отображения_ - отрезать подчерк.. систему-то мы по нему уже отрезолвили.

**Comment by tomarcafe** [comment]
почему _ - потому что цифры явно умеют использоваться в тикерах, подчерк же там явно левый елемент, т.е. добавляя подчерк - не внесём случайных запутанностей.

**Comment by 21xhipster** [comment]
А где у нас сейчас идет завязка на тикеры? Давай я сформулирую, как мне кажется у нас сейчас:
- Смотрим в рынки. Делаем уникальную пару имя + тикер. Сравниваем с Chanigear. Кладем в индекс
- Берем с индекса по нашему уникальному имени
- В приложении работаем с этим уникальным именем. Доп данные берем с Chaingear т.к. имя там уникально.
Я если честно не совсем понимаю откуда у нас возникает конфликт с тикерами, т.к. по дизайну от них вообще ничего не должно зависеть.

**Comment by tomarcafe** [comment]
хорошо давай переделаем..
я завязался на тикеры а не на ЧГ имена. 
ошибся, ок.

**Comment by 21xhipster** [comment]
Договорились.

**Comment by tomarcafe** [comment]
я говорю про то место где у нас инфа по акаунтам считаеся
тикеры там появились оттого что автоапдейт возвращал тикеры - 
ок, будем из тех тикеров резолвить сразу ЧГ имена, и при добавлении вручную тож их использовать.

но тогда получается что если кто сейчас забьёт портфель плотно - придется потом конвертить.. возможно, руками...

**Comment by tomarcafe** [comment]
хм. возможно, с этого места и начну..

**Comment by 21xhipster** [comment]
Для того Chaingear и задуман. Чтобы каждый раз, где это необходимо был источник правды. Пока у нас есть пять пользователей, можно всё. Если протянем, тогда получим в таких случаях доп. косты по конвертированию.

**Comment by tomarcafe** [comment]
угу
