### ISSUE TITLE
Display star and follow buttons for unregistered users

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#246]
Click lead to `/welcome`

**Comment by tomarcafe** [comment]
useless. won't work in any sense

**Comment by tomarcafe** [comment]
how would "follow" work?
how would "star" work?

**Comment by 21xhipster** [comment]
Just send them to /welcome page.
Does that possible to store action to execute it after user login?

**Comment by tomarcafe** [comment]
yes possible, ok a bit later, now moving again :)
