### ISSUE TITLE
Add Ranking to Rating

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#253]
В списке должен быть порядковый номер позиции

**Comment by tomarcafe** [comment]
поясни

**Comment by 21xhipster** [comment]
Циферку с номером в каждую строчку надо подставить

**Comment by 21xhipster** [comment]
Нужно привести отображение в порядок

**Comment by tomarcafe** [comment]
что это значит?

**Comment by 21xhipster** [comment]
Это означает, что мне нужно будет привести отображение в порядок! Я переназначил на себя!

**Comment by 21xhipster** [comment]
Спасибо!
