### ISSUE TITLE
Add Sign up / Log in button on Header

### ISSUE THREAD

**Issue by lomashuk** [cyberFund/cyber.fund#264]

**Comment by tomarcafe** [comment]
do i remove sign in button from 'portfolio' and  'radar' pages?

**Comment by lomashuk** [comment]
No

**Comment by lomashuk** [comment]
1. Name for button: Log In/Sign Up
2. Make sign in straight from header.(remove sign in page)

**Comment by lomashuk** [comment]
1. leave the name of the button log in
