### ISSUE TITLE
Fix errors in segment's event and page naming

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#286]
buttonClick => Discovered Charts
Clicked Cyberep External Link => Clicked External Link
Clicked Cyberep Social => Shared a Thing
Changed Amount => Updated Amount Manually
Delete Account => Deleted Account
Delete Address => Deleted Address
Delete Asset => Deleted Asset
Searched Data Redirect => Searched
Unfollowed system => Unfollowed System
Followed system => Followed System
Pages:
ProfileOld - Разобраться что это!?
Slide - Что это? Чем отличается от Cyberep?
Welocome => Welcome

**Comment by 21xhipster** [comment]
@lomashuk Unfollowed system не переименовано. Нужно для того, чтобы можно было делать выборку по интеракциям с объектами.

**Comment by lomashuk** [comment]
Все переименовано, просто событие называется Unfollowed System, как написано в задании
