### ISSUE TITLE
Icons for the added systems are not displayed

### ISSUE THREAD

**Issue by vitalylvov** [cyberFund/cyber.fund#300]
Для новых систем не отображаются картинки, при этом свойство `icon` прописано. Сначала думал что грешит на  jpg, но для png так же не работает. Примеры:
https://cyber.fund/system/Orb
https://cyber.fund/system/Bitnation

**Comment by tomarcafe** [comment]
да, сейчас это в ручном режиме синхронизируется
просто пиши лс когда понадобится снова

**Comment by vitalylvov** [comment]
ок

**Comment by tomarcafe** [comment]
create mode 100644 logos/bitnation.jpg
 create mode 100644 logos/blockapps.jpg
 create mode 100644 logos/c-cex.png
 create mode 100644 logos/indiesquare.png
 create mode 100644 logos/omniwallet.png
 create mode 100644 logos/orb.png
 create mode 100644 logos/rootstock.png
проверь снова
