### ISSUE TITLE
Radar loading time 10-20 seconds

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#303]

**Comment by 21xhipster** [comment]
![screen shot 2015-11-03 at 08 16 27](https://cloud.githubusercontent.com/assets/410789/10903604/6d1669d8-8203-11e5-9d15-18b1dd074464.png)

**Comment by tomarcafe** [comment]
cannot reproduce :) yet, it s of no doubt server is not tuned and slow and.. badly made, to be short
