### ISSUE TITLE
Add schema to system page

### ISSUE THREAD

**Issue by lomashuk** [cyberFund/cyber.fund#322]

**Comment by lomashuk** [comment]
Пример, будут вопросы пиши
<div itemscope itemtype="http://schema.org/Product">
  <span itemprop="name">bitcoin</span> 
  <span itemprop="alternateName">BTC</span> 
  <div itemprop="brand"
    itemscope itemtype="http://schema.org/Organization">
    <span itemprop="name">Bitcoin</span> 
  </div>
  <img src="bitoin.png" alt='Bitcoin' /> 
  <div itemprop="aggregateRating"
    itemscope itemtype="http://schema.org/AggregateRating">
   Rated <span itemprop="ratingValue">3.5</span>/5
  </div>
  <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
    
    <span itemprop="priceCurrency" content="BTC">Ƀ</span><span
          itemprop="price" content="3">3</span>
  </div>
  <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
    
    <span itemprop="priceCurrency" content="USD">$</span><span
          itemprop="price" content="1000.00">1,000.00</span>
  </div>
  Product description:
  <span itemprop="description">A peer-to-peer electronic cash</span> 
</div>

**Comment by tomarcafe** [comment]
а чего там не хватает сейчас?

**Comment by lomashuk** [comment]
Попробуй через валидатор прогнать https://webmaster.yandex.ru/microtest.xml
Этот код и тот, а так поправить нужно следующее:
aggregateRating
brand
и проверить offer

**Comment by tomarcafe** [comment]
ну единственное нарекание - это что цена в BTC  не распознается - т.е. оно не взодит в список валютных кодов

ну и брэнд - brand = Bitcoin 
совпадает практически с name - ну тут уж не знаю чем помочь.

**Comment by lomashuk** [comment]
Леша смотри здесь не так как у тебя:
 <div itemprop="aggregateRating"
    itemscope itemtype="http://schema.org/AggregateRating">
   Rated <span itemprop="ratingValue">3.5</span>/5
  </div>
 <div itemprop="brand"
    itemscope itemtype="http://schema.org/Organization">
    <span itemprop="name">Bitcoin</span> 
  </div>

**Comment by tomarcafe** [comment]
не понимаю. 
они ж считываются?

**Comment by tomarcafe** [comment]
я по яндексу вижу что считываются

**Comment by lomashuk** [comment]
Это хорошо что ты по яндексу видишь)! Но по схеме правильное написание на сколько я изучил, так как предлагаю я)

**Comment by tomarcafe** [comment]
ну поскольку я не очень понимаю как править - https://github.com/cyberFund/cyber.fund/blob/develop/client/views/widgets/portrait/systemBasic.html 
можно прямо на сайте гитхаба правки вносить

**Comment by lomashuk** [comment]
Точно также как в оффере) такая же вложенность

**Comment by tomarcafe** [comment]
не. давай сам. а то это затянется. 

если какой то элемент надо помочь найти - говори помогу, фаел то большой

**Comment by 21xhipster** [comment]
@lomashuk @tomarcafe Тоже самое. Нужно понять статус задачи. Закрываем? Или что-то нужно доделать? Это важная штука.

**Comment by tomarcafe** [comment]
закрываю. безотносительно пререндера - текущий вариант сайта эти элементы рендерит. нужно будет просто перенести это дальше. закрываю.
