### ISSUE TITLE
Add schema to public profile

### ISSUE THREAD

**Issue by lomashuk** [cyberFund/cyber.fund#323]
Example:
`<div itemscope itemtype="http://schema.org/Person">
  <span itemprop="name">Konstantin Lomashuk</span> 
  <span itemprop="alternateName">@lomashuk</span> 
  <img src="lomashuk.png" alt='Lomashuk' /> 
  <div itemprop="followee"
    itemscope itemtype="http://schema.org/Person">
    
    <span itemprop="name">Dima Starodubcev</span> 
    <span itemprop="url">https://cyber.fund/@21xhipster</span> 
  </div>
  <div itemprop="follows"
    itemscope itemtype="http://schema.org/Person">
    
    <span itemprop="name">Dima Starodubcev</span> 
    <span itemprop="url">https://cyber.fund/@21xhipster</span> 
  </div>
  <div itemprop="netWorth" itemscope itemtype="http://schema.org/PriceSpecification">
    
    <span itemprop="priceCurrency" content="USD">$</span>
    <span itemprop="price" content="1000.00">1,000.00</span>
    <span itemprop="name">Portfolio</span> 
  </div>
  <div itemprop="netWorth" itemscope itemtype="http://schema.org/PriceSpecification">
    
    <span itemprop="priceCurrency" content="BTC">Ƀ</span>
    <span itemprop="price" content="1000.00">1,000.00</span>
    <span itemprop="name">Portfolio</span> 
  </div>
  <div itemprop="owns"
    itemscope itemtype="http://schema.org/Product">
    
    <span itemprop="name">Bitcoin</span> 
    <span itemprop="url">https://cyber.fund/Bitcoin</span> 
  </div>
</div>`

**Comment by tomarcafe** [comment]
добавил разметку, в том числе и для фоловеров
но судя по тому что яндекс пишет - он фоловеров видит просто как других персон - не отдупляет свойство отношения - так что лучше это убрать мне так кажется, оставить только на сам профиль

**Comment by lomashuk** [comment]
view-source:https://cyber.fund/@21xhipster/?_escaped_fragment_=

смотри профиль вообще не содержит схему(
я по крайней мере ее не вижу
по поводу поля followee ты прав, убираем его)

**Comment by tomarcafe** [comment]
>смотри профиль вообще не содержит схему(
а знаешь почему?
потому что изменения вносятсыя в дев, а ты смотришь на мастер

**Comment by lomashuk** [comment]
) Значит надо мержить, так как в деве нет пререндера, а без него я проверить не могу)

**Comment by tomarcafe** [comment]
а я могу :) 
открываешь консоль разраба в браузере (F12), выбираешь инспектора, в нем выбираешь корневую ноду (<html>), кликаешь правой мышой, говоришь copy outer html - и несешь в яндексовскую тулзу. а мержить будем когда по ее результатам вопросов не останется, ок?

**Comment by lomashuk** [comment]
1. alternatename там не должно быть не ссылки не текста там должно быть вот так

**Comment by lomashuk** [comment]
2. Вот эти поля вообще отсутствуют:
``` <img src="lomashuk.png" alt='Lomashuk' /> <!-- twitter image  -->
  <div itemprop="follows"
    itemscope itemtype="http://schema.org/Person">
    <!-- Following -->
    <span itemprop="name">Dima Starodubcev</span> <!-- name -->
    <span itemprop="url">https://cyber.fund/@21xhipster</span> <!-- url -->
  </div>
  <div itemprop="netWorth" itemscope itemtype="http://schema.org/PriceSpecification">
    <!-- price of portfolio in USD -->
    <span itemprop="priceCurrency" content="USD">$</span>
    <span itemprop="price" content="1000.00">1,000.00</span>
    <span itemprop="name">Portfolio</span> <!-- Portfolio -->
  </div>
  <div itemprop="netWorth" itemscope itemtype="http://schema.org/PriceSpecification">
    <!-- price of portfolio in BTC -->
    <span itemprop="priceCurrency" content="BTC">Ƀ</span>
    <span itemprop="price" content="1000.00">1,000.00</span>
    <span itemprop="name">Portfolio</span> <!-- Portfolio -->
  </div>
  <div itemprop="owns"
    itemscope itemtype="http://schema.org/Product">
    <!-- system in portfolio -->
    <span itemprop="name">Bitcoin</span> <!-- token_name -->
    <span itemprop="url">https://cyber.fund/Bitcoin</span> <!-- url -->
  </div>```

**Comment by tomarcafe** [comment]
так они у нас и на странице отсутствуют. не добавляй в схему то чего нет на сайте

**Comment by tomarcafe** [comment]
ok alternateName поправил

**Comment by 21xhipster** [comment]
@lomashuk Я так и не понял, что сделано по этому вопросу, а что не сделано. Мы его закрываем или нет?

**Comment by tomarcafe** [comment]
еще надо будет пройтись по существующим ишуям и составить из них спецификацию на новую веб-апликуху :)
