### ISSUE TITLE
Forward segment event stream to Meteor app also

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#324]
Will enable integration of event streams

**Comment by 21xhipster** [comment]
@tomarcafe Хочу начать обсуждение того, как мы будем реализовывать фиды (ну типа кто, что и как сделал). Предлагаю тупо перенаправить поток имеющихся в Segment ивентов внутрь бд метеора. Это даст возможность, например, выводить каждому юзеру страницу с ивентами людей, которых он фоловит достаточно просто.

**Comment by tomarcafe** [comment]
хм.
