### ISSUE TITLE
Events doesn't work correctly

### ISSUE THREAD

**Issue by lomashuk** [cyberFund/cyber.fund#337]
<img width="517" alt="2015-11-25 12 36 16" src="https://cloud.githubusercontent.com/assets/8813296/11395018/35b07a5e-9371-11e5-8b65-1a06de7b3a79.png">

События page приходит, а title и url не верный

**Comment by tomarcafe** [comment]
насколько я понял, сейчас починилось - **за исключением того что** `url` теперь называется `__url__`

**Comment by 21xhipster** [comment]
Я проверял. Не починилось. 
![screen shot 2016-02-19 at 10 45 49](https://cloud.githubusercontent.com/assets/410789/13173539/04e7238c-d6f6-11e5-9d4b-556979b353a7.png)
И вообще у нас какой-то пиздец с `url` Их три.

**Comment by tomarcafe** [comment]
действительно, не починилось..

**Comment by tomarcafe** [comment]
давайте ещё скриншотов

**Comment by 21xhipster** [comment]
А че решил вынести из главных?

**Comment by tomarcafe** [comment]
статус?
