### ISSUE TITLE
Segment don't work for two weeks

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#350]
![screen shot 2016-01-13 at 23 42 54](https://cloud.githubusercontent.com/assets/410789/12311557/bf407382-ba4f-11e5-93f5-8c19f8dcc5b7.png)

**Comment by tomarcafe** [comment]
![segment](https://cloud.githubusercontent.com/assets/1535817/12316612/7faffbec-baaa-11e5-8218-b5b49cccf924.png)

seems working, at least debugger realtimes events

**Comment by tomarcafe** [comment]
is working now, no?
