### ISSUE TITLE
Merge Portfolio and Profile page

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#357]
Смысл какой. Сейчас у нас есть две страницы которые показывают приблизительно одно и тоже. Нужно их слить следующим образом: на профиле сделать две вкладки. В одном - overview портфеля как сейчас на странице Portfolio, на другом - настройка адресов. По отзывам то что сейчас очень сильно путает людей. Работы на пару часов - а юзабилити результат - дикий.

**Comment by tomarcafe** [comment]
@21xhipster  @lomashuk  каменты по текущему решению будут?

**Comment by 21xhipster** [comment]
@tomarcafe А где с текущим решением можно ознакомиться? На dev все как было так и есть.

**Comment by tomarcafe** [comment]
так. а шо там щас? не зватает таблицына своём профиле, такой какая на чужом, так я вижу? что ещё?

**Comment by 21xhipster** [comment]
Счета с адресами бы перенести во в таб. Давай нарисую.
