### ISSUE TITLE
Automatic balance autoupdate

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#358]
На данный момент нужно для автоапдейта балансов нажимать кнопку. Нужно сделать так, чтобы такой кнопки в принципе не было. Вместо этого нужно информировать юзера когда последний раз был сделан апдейт баланса.

**Comment by tomarcafe** [comment]
и? сколь часто обновляться?
кстати насчёт убрать кнопку - дурацкая идея же.

нопремер сижу я и жду когда мне платёж придёт. чё б это не делать на dev.cyber.fund ?

**Comment by 21xhipster** [comment]
Можно оставить. Но только одну на все. Это не должно быть основным способом обновления балансов. Надо научиться делать это так, чтобы юзер об этом не думал.
