### ISSUE TITLE
Display icons of the systems

### ISSUE THREAD

**Issue by deltaidea** [cyberFund/cyber.fund#36]
Should show icons for each system.

Implementation steps:

- [x] Create/find a default icon for systems without one
- [x] Add icons to `public/icons/` with file names set as `name-symbol.png`, where `name` is system name, and `symbol` is system symbol (short name). E.g. `Bitcoin-BTC.png`. This is because neither name, nor symbol is unique, but their pair is.
- [ ] Show the icons in the rating table.

**Comment by deltaidea** [comment]
Please reassign me to this issue once the icons are ready, so I can code them in.

**Comment by 21xhipster** [comment]
What about [this](http://4.bp.blogspot.com/-Xsbd1jB28S0/VMuL2jwhUWI/AAAAAAAAEDc/kaFm7dhh6vo/s1600/work%2Bin%2Bprogress.png) default icon for systems?

**Comment by deltaidea** [comment]
Good, except the work isn't in progress. Nobody's gonna create icons for 600+ systems, right?
Let's try no icon at all for systems without one.

**Comment by 21xhipster** [comment]
Why? Our json is open. So everybody can add!
