### ISSUE TITLE
Implement new price feeds on system page

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#360]
Я вижу это похожим на то, что есть сейчас на Cryptocompare.
тут https://www.cryptocompare.com/coins/btc/markets/USD и тут https://www.cryptocompare.com/coins/btc/analysis/USD
@vitalylvov @lomashuk @tomarcafe - прошу присоединиться к обсуждению того, каким вы это хотите видеть

**Comment by tomarcafe** [comment]
closing this. 

should, however, somehow use multiple data sources for charts
