### ISSUE TITLE
Daily automatic CMGR and Rating recalculations

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#362]

**Comment by 21xhipster** [comment]
А если мы сделаем это дело каждый час - сильно это нас нагрузит?

**Comment by tomarcafe** [comment]
не знаю. смысл? на зв1здочки и так пересчёт сразу. ты думаешь если ты каждый час будешь пересчитывать cmgr это типа офигенно точность добавит7

**Comment by 21xhipster** [comment]
Смысл есть. Если по звездочкам нет, то CMGR - точно.
Я вот когда что-то резко вырастает в цене - первой что мне надо посмотреть - это какую доходность этот актив имеет при текущей цене. И день я не могу ждать. Час еще куда боль менее. Если по рейтингу - это ресурсоемко - то давай рейтинг оставим раз в день. А вот CMGR хотелось бы раз в час.

**Comment by tomarcafe** [comment]
ну давай сделаем каждый час.
