### ISSUE TITLE
Change logic of displaying systems in Rating

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#364]
Мое предложение следующее:
- [ ] Скрывать из рейтинга системы с рейтингом менее 2. Таким образом весь шрот уйдет. По системам которые надо отображать но рейтинг не дотягивает нужно будет просто поработать над контентом.
- [ ] Убрать пагинацию из рейтинга, так систем с рейтингом менее 2 немного.
- [ ] Вместо Discover Opportunities которая отображает дополнительные системы сделать кнопку Show All Systems которая будет вести на Tracking.
@vitalylvov @lomashuk Хотелось бы услышать ваше мнение

**Comment by tomarcafe** [comment]
не ну тогда уж не кнопку а ссылку

**Comment by 21xhipster** [comment]
Да. Можно и ссылку.

**Comment by tomarcafe** [comment]
гг на локал машине осталось 3 (три) системы с рейтингом больше 2.

**Comment by 21xhipster** [comment]
Ну там же нету звездочек :-)

**Comment by tomarcafe** [comment]
хочется ответить "хуёздочек" - но я сдержусь.
