### ISSUE TITLE
AIP and VWAP don't displayed in Tracking

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#365]

**Comment by tomarcafe** [comment]
по русски напиши. не понятно чего надо.

**Comment by 21xhipster** [comment]
А че там непонятно. Нету цифр
![screen shot 2016-02-16 at 17 21 26](https://cloud.githubusercontent.com/assets/410789/13084571/c660b306-d4d1-11e5-9a2d-0c3d672a6b77.png)

**Comment by tomarcafe** [comment]
что это за цифры?
мне ваще ниче сокращения не говорят
ладно vwap допустим у нас ещё нету вооще. че такое aip ?

**Comment by 21xhipster** [comment]
Average Initial Price. В заголовке же есть!

**Comment by tomarcafe** [comment]
ну aip можно добавить, а вторая будет ждать пока у нас данные с апи не начнут подходить

**Comment by 21xhipster** [comment]
![screen shot 2016-03-17 at 11 19 58](https://cloud.githubusercontent.com/assets/410789/13844554/3d63cbb0-ec32-11e5-81d9-4fe1c3f9ef94.png)
@tomarcafe А давай всё таки эту штуку поправим.
1. Вообще непонятно в каком формате выводится AIP.
2. WVAP - туда нужно просто ставить цену. Из Coinmarketcap сейчас приходит цена взвешенаая на объемы.

**Comment by 21xhipster** [comment]
Добавить:
- выравнивание по правому краю
- две цифры после запятой нормальным текстом и еще 3 более мелким серым
