### ISSUE TITLE
Add url for sorting option in Rating

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#367]

**Comment by tomarcafe** [comment]
какие ваши варианты? я к тому, что нужны альясы. ЧПУ и вот это вот всё.потому что ключи, которые используются для сортировки (а по факту пути до полей сортировки) нечитабельны 
такшта кидай список. ну и как это вообще будет? ?sort=months_asc (?sort=months) || ?sort=months_desc; либо направление сортировки указывать отдельным параметром. 

чота я не втыкаю как лучче.

**Comment by tomarcafe** [comment]
т.е. как минимум придумать прикольные названия для всех ключей, как максимум помочь определиться мне со схемой по которой из urlparams достаются ключи (ну и складываются туда тоже.. )

**Comment by 21xhipster** [comment]
Url должны быть следующими:
`
cyber.fund/rating/whales and cyber.fund/rating/by-dolphins - Cap
cyber.fund/rating/active and cyber.fund/rating/passive - Trade
cyber.fund/rating/bulls and cyber.fund/rating/bears - 1d change
cyber.fund/rating/leaders and cyber.fund/rating/suckers - Tating
cyber.fund/rating/profit or cyber.fund/rating/loss - CMGR
cyber.fund/rating/popularity or cyber.fund/rating/silence - Star
cyber.fund/rating/inflation or cyber.fund/rating/deflation - Token
`
Вот так будет пиздато.

**Comment by tomarcafe** [comment]
завизируй у @mguryeva :)

**Comment by 21xhipster** [comment]
Давай захерачим! Если @mguryeva будет против, я уже сам смогу откорректировать!

**Comment by tomarcafe** [comment]
лан.
щас пытаюсь просто масштаб бедствия оценить

**Comment by mguryeva** [comment]
Визирую :) Клевые сортировки ... Надо только на будущее unicorns обязательно иметься flops для тех, кто мегакруто растёт, и тех, кто заваливается

**Comment by 21xhipster** [comment]
@mguryeva unicorns - это скорее не сортировки а фильтры. Ну типа > 1B. А вот flops пока даже нет идей как выделить.
