### ISSUE TITLE
Ripple Cap somehow become incorrect

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#373]
Now its calculated based on CMC supply. It should be calculated based on supply from Chaingear. Week ago it was ok

**Comment by tomarcafe** [comment]
put 'supply_from_here: true' to chaingear.

**Comment by 21xhipster** [comment]
I've checked before. Its there

**Comment by tomarcafe** [comment]
seems that s because cyber.fund and dev.cyber.fund are out of sync.
