### ISSUE TITLE
Remove `BR`calculation

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#383]
Пока мы не дошли до такого дзена как индексация заголовков блоков - этот показатель наверное лучше обнулить, т.к. из-за того, как у нас вычисляется сейчас (я помню это я так придумал) у нас много каких систем вылетает в трубу. Давай пока уберем. Хотя сам столбик пусть остается с нулями.

**Comment by tomarcafe** [comment]
хорошо, уберу. 
server/calculables/lib/params.js - тут надо будет подкрутить - кстати, я  по нему вижу, что GR не используется. раз так - GR я тоже не показываю.
