### ISSUE TITLE
Registration using Emals

### ISSUE THREAD

**Issue by lomashuk** [cyberFund/cyber.fund#386]

**Comment by tomarcafe** [comment]
не очсень понятны детали. ну типа, как у нас профиль-то будет работать?
не очень понятно мне также, как там правильно мержить аккаунты

**Comment by 21xhipster** [comment]
Эту штуку мы зафиксировали, но не сформулировали. Дай нам с @lomashuk подумать как правильно это реализовать.

**Comment by tomarcafe** [comment]
feature added 
things left: 
 1. validdate email (if needed, as email users restricted from using public functions - maybe not needed right now) 
 2. restrict from using public accounts
 3. adopt starring systems so stars won t count for email users
