### ISSUE TITLE
Fix links on system page

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#387]
- [x] Сделать ссылки на News плашками как ссылки приложений
- [ ] Сделать весь текст ссылки кликабельным. Сейчас кликнуть можно только по нескольким пикселям

**Comment by tomarcafe** [comment]
вот про "весь текст" не понял .где это вообще происходит

**Comment by 21xhipster** [comment]
Вот сейчас вроде ок уже.
