### ISSUE TITLE
Safex is not shown in tracking and rating

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#395]

**Comment by tomarcafe** [comment]
because it s marked via `flags.rating_do_not_display: true`
i think it s ok this flag disables /tracking display as well .

**Comment by 21xhipster** [comment]
That is not a true. I've remove this flag 2 weeks ago

**Comment by tomarcafe** [comment]
hmmm. let s set it to false :)
thing is how mongo' $set operator works :) so once field is set, removing resp. key won't clear it
