### ISSUE TITLE
Safex CMGR is not calculated

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#396]

**Comment by tomarcafe** [comment]
https://github.com/cyberFund/chaingear/blob/gh-pages/sources/Safex/Safex.toml why am i not surprised?

how would it be calculated from this dataset?
correct, no way.

**Comment by 21xhipster** [comment]
Oh, yeah. Reassigned to @vitalylvov

**Comment by vitalylvov** [comment]
done https://github.com/cyberFund/chaingear/commit/50e8cc6676280e018674d6024ffb672b4199e06d

**Comment by 21xhipster** [comment]
Don't work anyway. As well as hook https://cyber.fund/hooks/chg-update
