### ISSUE TITLE
Funds Page

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#402]
Simple list of users (as in Rating) by default sorted by followers with ability to sort by Asset Under Management with the following fields:
- Name of a user
- Number of followers 
- You follow mark
- Amount of Assets (don't inclued zero's)
- AUM in BTC
- AUM in USD

Filter users with zero followers and zero assets

**Comment by tomarcafe** [comment]
url?

**Comment by 21xhipster** [comment]
Gues :-) `/funds`

**Comment by 21xhipster** [comment]
Можно конечно выебнуться... Типа https://cyber.fund/s Но я думаю никто не оценит :-)
