### ISSUE TITLE
Social login

### ISSUE THREAD

**Issue by phideas** [cyberFund/cyber.fund#415]
Social login should respect Profile updates. Cyber.fund should offer simple profile updates too.
https://cyber.fund/@phideas_design
https://twitter.com/phideas_

**Comment by tomarcafe** [comment]
Thanks for the feedback. 
Seems like fixed now. Please let us know if it is really fixed or just seems

**Comment by phideas** [comment]
Handle is fixed. Please solve the name update somehow too. Thanks!

**Comment by tomarcafe** [comment]
@phideas  
sorry for hanging this for almost a week. and many thanks for submitting a bug.

**Comment by phideas** [comment]
Fixed, Thanks!
