### ISSUE TITLE
Public profile do not display 

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#418]
https://cyber.fund/@ITarutov39

**Comment by tomarcafe** [comment]
done. some other issues like this may arise. 
we d have some texto about this.

**Comment by tomarcafe** [comment]
Dear user!. If you experience some accounts are missing - let us know. basically, link to your profile (or twitter profile :) ) is enough

**Comment by tomarcafe** [comment]
ok, seems i ve figured this out and fixed. 

accounts that contained only manual values become deleted on balance update. now fixed. will reimport all soon. seems there s only 4-5 accounts/addresses added yesterday, so bulk operation is ok
