### ISSUE TITLE
Public Profile: Missing Account Data

### ISSUE THREAD

**Issue by matthewjamesr** [cyberFund/cyber.fund#419]
Missing multiple coin's information, addresses, balances, etc.

[@matthewjamesr](@matthewjamesr)

**Comment by tomarcafe** [comment]
Checked out. Seems like we've lost changes made from May 5 till May 6. 
I only see 1 pubic account (and no privates) with 5 addresses, one of them containing manually added data.
Most probably you ve added multiple data yesterday? 
I m sorry, but the only way is to add this again.. 

currently i m checking if it all works ok

**Comment by tomarcafe** [comment]
also seems like balance calculation fails. i see you have bitcoins listed, but they do not count

**Comment by matthewjamesr** [comment]
Everything is manually added with the exception of any XCP/BTC under my Counterparty address. Will have to wait till tonight to re-add the data.

**Comment by tomarcafe** [comment]
Sorry about this.

**Comment by matthewjamesr** [comment]
No worries, still love your service.

**Comment by tomarcafe** [comment]
actually, storing data is fixed now.
