### ISSUE TITLE
Run our own nodes

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#437]
cyberFund has demand in indexing of leading blockchains. As of now search of objects (block, transaction, address, token, name) by hash across all blockchains is impossible. That fact significantly complicates development of multiblockchain apps. We are suffering from this ourselves, trying to implement a simple task of balance querying for 40 leading blockchain tokens. Currently we solve it analyzing addresses by regular expressions. This solution allow us to suggest in which blockchain node we should route a query. It turned out unreliable, non-stable and insufficient. To solve this task we are going to index all objects hashes across leading blockchains saving information of objects'  locations. This enable us to create API with only 2 simple methods: 
1. indexBlock. Put method that parse blocks content effectively saving all objects locations. Available to trusted partners.
2. searchHash. Get method which return object with all attributes. Available for anybody.

We believe that such API significantly reduce hassle of developing multiblockchain applications for the following categories:
- Wallets
- Exchanges
- Analytics services
- Search engines
- Institutions

Implications: Industry experts forecast fast growth of blockchain ecosystems across governments, institutions and technology companies due to unique value proposition of blockchains in terms of transactional security and efficiency for any kind of digital property objects. We think of this project as of Google for digital property. Thus it scales perfectly.

But we need computing power that we cannot afford. We didn't monetize our growing service yet.

This are blockchain nodes we need to indexing first:
- Bitcoin. 16 GB RAM. 1 TB Storage
- Ethereum. 4 GB RAM. 1 TB Storage
- Steem. 2 GB RAM. 100 GB Storage
- BitShares. 2 GB RAM. 100 GB Storage
- Counterparty on top of Bitcoin core. 16 GB RAM. 100 GB Storage
- OmniLayer on top of Bitcoin core. 8 GB RAM. 100 GB Storage
- Augut on top of Ethereum. 4 GB RAM. 10 GB Storage
- Ripple. 16 GB RAM. 100 GB Storage
- Sia. 4 GB RAM. 10 GB Storage
- Dash. 4 GB RAM. 10 GB Storage
- NEM. 4 GB RAM. 10 GB Storage
- Lisk. 4 GB RAM. 100 GB Storage
- Monero. 4 GB RAM. 10 GB Storage
- Factom. 2 GB RAM. 10 GB Storage
- Stellar. 8 GB RAM. 100 GB Storage
- NXT. 4 GB RAM. 10 GB Storage
- Gridcoin. 4 GB RAM. 10 GB Storage
- Dogecoin. 4 GB RAM. 100 GB Storage
- Litecoin. 4 GB RAM. 100 GB Storage
- Peercoin. 4 GB RAM. 100 GB Storage
- Emercoin. 4 GB RAM. 10 GB Storage
- Namecoin. 4 GB RAM. 100 GB Storage
- Decred. 4 GB RAM. 100 GB Storage

Blockchain nodes has been selected based on our unique [methodology of crypto property evaluation](https://www.academia.edu/22691395/cyber_Rating_Crypto_Property_Evaluation) reviewed by industry experts including Vitalik Buterin. Live evaluation is [presented here](https://cyber.fund/rating/leaders).

Also we need standalone search index to run on top of BigChainDB that is a private blockchain. Presumably that is about 64 GB RAM and 1 TB Storage more.

Total 196 GB RAM, 4 TB Storage.
We suppose demand on computing and storage can growth twice in a year.

This project is fully opensource under MIT license and will encourage developers participate and add compliant templates to Microsoft Azure templates collection. In case of successful implementation cyberFund will showcase possibilities behind Azure BaaS solutions for startup ecosystem.

Monetization of API is possible in 2 years. We suppose this time will be enough to demonstrate successful showcases thus effectively creating demand.

**Comment by 21xhipster** [comment]
@tomarcafe Thanks! Updated

**Comment by tomarcafe** [comment]
closing?

**Comment by 21xhipster** [comment]
Let's transform it

**Comment by tomarcafe** [comment]
summary: 
4TB hdd
>128+ GB ram

**Comment by 21xhipster** [comment]
[Отдельный проект](https://github.com/orgs/cyberFund/projects/1)
