### ISSUE TITLE
Add non-compliant and Not Verified marks to Radar page

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#441]

**Comment by Undeadlol1** [comment]
@21xhipster
https://github.com/cyberFund/cyber.fund/commit/ac04b5749fea3735201cf05556c558c0f4d58afb

**Comment by Undeadlol1** [comment]
@21xhipster https://github.com/cyberFund/cyber.fund/commit/748a0d0cf12fc07616f4dbc722e1aa95eefc479b
Seems like this issue needs to be closed
