### ISSUE TITLE
ICO Radar doesn't update

### ISSUE THREAD

**Issue by ninjascant** [cyberFund/cyber.fund#465]
We can't add new projects to https://cyber.fund/radar because site doesn't fetch new data from Chaingear repo after [chaingear.json](https://github.com/cyberFund/chaingear/blob/gh-pages/chaingear.json) update

**Comment by abitrolly** [comment]
/CC @litvintech

@ninjascant how do you test that data is not there? Posting specific link helps.

**Comment by ninjascant** [comment]
@abitrolly For example: https://cyber.fund/system/Cryptics ICO start date: December 9, 2017,Saturday (wrong); ICO start date in chaingear.json: 2018-03-26T00:00:00 (right)

**Comment by abitrolly** [comment]
@tomarcafe found the problem in invalid chaingear data that doesn't provide `system` field used as database id. He pointed to https://github.com/cyberFund/chaingear/blob/gh-pages/scripts/testDuplicates.js script and helped me modify it to detect these errors, so I am working on CI solution right now.

For example, one of the culprits is https://github.com/cyberFund/chaingear/commit/0f2c778cbdbb46ed2d766ca51d89e4d82c7b2f43#diff-ab6d027496f54ee71391566b49df8027 Where is this form that you use to commit data to chaingear?

**Comment by abitrolly** [comment]
@ninjascant can you detect when this form/script started working? Probably that was the time when everything got broken. )

**Comment by abitrolly** [comment]
I've added CI with two checks that @tomarcafe created. They will run on every PR and mark it as broken if any data is wrong. If you open https://github.com/cyberFund/chaingear there is a status badge too.

Here is the list of chaingear that should be fixed - https://travis-ci.org/cyberFund/chaingear/builds/326953983#L462

**Comment by ninjascant** [comment]
@abitrolly @tomarcafe Thank you for explanation. The problem was that "invalid" data is our new data structure for Chaingear. To be displayed on site this new objects is converted into the old structure with `system` and other fields by [this script](https://github.com/cyberFund/chaingear-golos-bot/blob/master/app/routes/commit-route.js). And it seems that once this scripts added duplicates in chaingear.json
I've added check for duplicates and empty objects in my script, and indeed, it finds 3 such objects, as we can see from this diff: https://github.com/cyberFund/chaingear/commit/4baa5f4a60c77761ca197386d679b8ab7953e6fc. After deleting this objects, all works fine
