### ISSUE TITLE
Fix tooltips of the first element in the list

### ISSUE THREAD

**Issue by deltaidea** [cyberFund/cyber.fund#58]
List headers overlap the tooltip, so it's only partially visible. Should be rendered on top.

**Comment by deltaidea** [comment]
Oops, accidentally closed the wrong issue with that commit.

**Comment by deltaidea** [comment]
See: https://github.com/Polymer/core-tooltip/issues/24

**Comment by 21xhipster** [comment]
May be it is better to show it from the left?
