### ISSUE TITLE
Make up for side menu

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#65]
Should looks like ![this](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Screen%20Shot%202015-05-12%20at%2019.32.17-8f2221bff822251095bdcbc68858f63a478b810c2beeeaf38ca397399f2bf4c0.png)

**Comment by tomarcafe** [comment]
однако, там не все ссылки же. обрати внимание, что боковое меню оформляется отдельно. не знаю зачем так сделано - но так велит манул по матерьялизу
