### ISSUE TITLE
Icons of systems with symbols in names

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#67]
![Random picture](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Screen%20Shot%202015-05-12%20at%2019.42.00-573287c136b692cb966184990298d0333e7c3d1eff423cf0321c4989e6730d69.png) shows

**Comment by 21xhipster** [comment]
Maybe better to switch to the names with absolute paths from meta descriptions?

**Comment by tomarcafe** [comment]
well, as this is edge case, i think we could resolve file name as
```
filename = meta.iconfilename || name
```
i.e. use plain old where it works, and use extra field with explicit filename, where it is provided for the currency
